ERR(PUMA_NOERR, "No error has occurred"),
ERR(PUMA_OSERROR, "The OS returned an error"),
ERR(PUMA_ERROR_SHORT_FILE, "The data file is missing data"),
ERR(PUMA_ERROR_INVALID_DATA, "The data in the file is invalid"),
ERR(PUMA_ERROR_OOB, "The X or Y axes from the data file are too large or one of them is not greater than 0."),
ERR(PUMA_ERROR_BAD_CMD_ARG_NEG, "Every coefficient should greater than 0."),
ERR(PUMA_ERROR_BAD_CMD_ARG_DEL_T, "Value of delta_t should be nonegative and less than 1."),
ERR(PUMA_ERROR_BAD_CMD_ARG_WO_IN, "The write out interval should be greater than 0 and less than number of iterations."),
